name: learn-github-workflows
run-name: ${{ github.actor }} is learning this stuff.
on: [push]
jobs:
  job_1:
    name: check bats version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  job_2:
    name: Save output as artifact
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: upload outputs file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
  job_3:
    name: Download artifact
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download output.log file
        uses: actions/download-artifact@v3
        with: output-log-file