name: learn-github-workflows
run-name: ${{ github.actor }} is learning this stuff.
on: [push]
env:
  my_name: Antti
  my_address: Salmintie
jobs:
  job_1:
    name: check bats version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  job_2:
    name: Save output as artifact
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 8 > output.txt
      - name: upload outputs file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.txt
  job_3:
    name: Download artifact
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download output.log file
        uses: actions/download-artifact@v3
        with: 
          name: output-log-file
      - name: print to console
        run: cat output.txt
      - name: the job succeeded
        if: ${{ success() }}
        run: echo success
  job_4:
    name: Dump contexts 
    runs-on: ubuntu-latest
    steps:
      - name: dump gh context
        id: gh_context_step
        run: echo '${{ toJSON(github) }}'
      - name: dump job context
        run: echo '${{ toJSON(job) }}'
      - name: dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: dump strategy context
        run: echo '${{ toJSON(strategy) }}'   
      - name: dump env context
        run: echo '${{ toJSON(env) }}'
  job_5:
    name: Print env to console
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: echo 'Hello ${{ env.my_name }}'   
      - name: print address
        run: echo 'Address is ${{ env.address }}'
  job_6:
    name: output practice
    runs-on: ubuntu-latest
    steps:
      - name: set output
        id: set_output
        run: echo 'oneword=test_value' >> GITHUB_OUTPUT
      - name: read output
        run: echo '${{ steps.set_output.outputs.oneword }}'