name: learn-github-workflows
run-name: ${{ github.actor }} is learning this stuff.
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  artifact-test:
    name: Save output
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: upload outputs file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log