name: Reusable workflow (called)

on:
  workflow_call:
    outputs:
      firstword:
        description: 'The first output string'
        value: ${{ jobs.reusable-workflow-test-job.outputs.output1 }}
      secondword:
        description: 'The second output string'
        value: ${{ jobs.reusable-workflow-test-job.outputs.output2 }}


jobs:
  reusable-workflow-test-job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=moi" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=maalima" >> $GITHUB_OUTPUT